import { type RouteConfig, index, route } from "@react-router/dev/routes";
import { extensionRoutes } from "./extensions/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/auth.login.tsx"),
  route("signup", "routes/auth.signup.tsx"),
  route("logout", "routes/auth.logout.tsx"),
  route("w", "routes/workspace.tsx"),
  route("w/recent", "routes/workspace.recent.tsx"),
  route("w/favorites", "routes/workspace.favorites.tsx"),
  route("w/folder/:folderId", "routes/workspace.folder.$folderId.tsx"),
  route("w/doc/:id", "routes/workspace.doc.$id.tsx"),
  route("w/:slug", "routes/workspace.legacy.$slug.tsx"),
  route("w/:slug/doc/:id", "routes/workspace.legacy-doc.tsx"),
  route("w/:slug/folder/:folderId", "routes/workspace.legacy-folder.tsx"),
  route("t/:workspaceId", "routes/teamspace.tsx"),
  route("t/:workspaceId/folder/:folderId", "routes/teamspace.folder.$folderId.tsx"),
  route("t/:workspaceId/doc/:id", "routes/teamspace.doc.$id.tsx"),
  route("t/:workspaceId/recent", "routes/teamspace.recent.tsx"),
  route("t/:workspaceId/favorites", "routes/teamspace.favorites.tsx"),
  route("t/:workspaceId/trash", "routes/teamspace.trash.tsx"),
  route("t/:workspaceId/members", "routes/teamspace.members.tsx"),
  route("s/:token", "routes/s.$token.tsx"),
  route("groups", "routes/groups.tsx"),
  route("groups/:groupId", "routes/groups.$groupId.tsx"),
  route("shared", "routes/shared.tsx"),
  route("trash", "routes/trash.tsx"),
  route("shared/folder/:folderId", "routes/shared.folder.$folderId.tsx"),
  route("shared/doc/:id", "routes/shared.doc.$id.tsx"),
  route("admin", "routes/admin.tsx"),
  route("settings", "routes/settings.tsx"),
  route("api/health", "routes/api.health.ts"),
  route("api/healthz", "routes/api.healthz.ts"),
  route("api/notifications", "routes/api.notifications.ts"),
  route("api/doc-download/:id", "routes/api.doc-download.$id.ts"),
  route("api/doc-preview/:id", "routes/api.doc-preview.$id.ts"),
  route("api/doc-versions/:id", "routes/api.doc-versions.$id.ts"),
  route("api/doc-history/:id", "routes/api.doc-history.$id.ts"),
  route("api/doc-shares/:docId", "routes/api.doc-shares.$docId.ts"),
  route("api/folder-shares/:folderId", "routes/api.folder-shares.$folderId.ts"),
  route("api/workspace-export/:id", "routes/api.workspace-export.$id.ts"),
  route("api/admin-user-export/:userId", "routes/api.admin-user-export.$userId.ts"),
  route("api/doc-pdf/:id", "routes/api.doc-pdf.$id.ts"),
  route("api/doc-docx/:id", "routes/api.doc-docx.$id.ts"),
  route("api/user-search", "routes/api.user-search.ts"),
  route("api/search", "routes/api.search.ts"),
  route("api/client-error", "routes/api.client-error.ts"),
  route("api/upload", "routes/api.upload.ts"),
  route("api/uploads/:file", "routes/api.uploads.$file.ts"),
  route("api/folder-children/:workspaceId", "routes/api.folder-children.$workspaceId.ts"),
  route("api/sidebar-data/:workspaceId", "routes/api.sidebar-data.$workspaceId.ts"),
  ...extensionRoutes,
] satisfies RouteConfig;
